<?php
$typeArr[1] = '关于我们';
$typeArr[2] = '机械产品';
$typeArr[3] = '行业优势';
$typeArr[4] = '新闻动态';
$typeArr[5] = '人力资源';
$typeArr[6] = '联系我们';
$typeArr[7] = '公司简介';
$typeArr[8] = '公司文化';
$typeArr[9] = '在线留言';
$typeArr[10] = '资质认证';
$typeArr[11] = '联系我们';
$typeArr[12] = '混凝土搅拌系列';
$typeArr[13] = '稳定土搅拌系列';
$typeArr[14] = '乳化分散搅拌系列';
$typeArr[15] = '搅拌机配件';
$typeArr[16] = '先进工艺';
$typeArr[17] = '质量优势';
$typeArr[18] = '优质管理';
$typeArr[19] = '公司动态';
$typeArr[20] = '业界资讯';
?>