<?php
$z[0]=Array("field","",133,161);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",186,215);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",217,246);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n                        <li><a href=\"[field:typelink/]\"  title=\"[field:typename/]\" target='_self'>[field:typename/]</a></li>\r\n                        ",351,557);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>