<?php
$z[0]=Array("field","",75,103);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",112,141);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",155,184);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",281,310);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("field","",445,473);
$z[4][4]=array();
$z[4][4]['name']="typeurl";
$z[5]=Array("channel","\r\n                                <a href=\"[field:typelink/]\" target='_self' title=\"[field:typename/]\" class='dropdown-item  navlist-2'>[field:typename/]</a>  \r\n                                ",597,844);
$z[5][4]=array();
$z[5][4]['type']="son";
$z[5][4]['noself']="yes";

?>