<?php
$z[0]=Array("field","",156,184);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",193,222);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",236,265);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",362,391);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("field","",526,554);
$z[4][4]=array();
$z[4][4]['name']="typeurl";
$z[5]=Array("channel","\r\n                                <a href=\"[field:typelink/]\" target='_self' title=\"[field:typename/]\" class='dropdown-item  navlist-2'>[field:typename/]</a>  \r\n                                ",678,925);
$z[5][4]=array();
$z[5][4]['type']="son";
$z[5][4]['noself']="yes";

?>