<li class="media media-lg border-bottom1">
								<div class="media-left">
									<a href="[field:arcurl/]" title="[field:title/]" target=_self>
										<img class="media-object"     src="[field:picname/]" alt="[field:title/]" height='100'>
									</a>
								</div>
								<div class="media-body">
									<h4>
										<a href="[field:arcurl/]" title="[field:title/]" target=_self>[field:title/]</a>
									</h4>
									<p class="des font-weight-300">
										[field:description function="cn_substr(@me,80)"/]...</p>
									<p class="info font-weight-300">
										<span>[field:pubdate function="GetDateTimeMK(@me)" /]</span>
										<span></span>
										<span>
											<i class="icon wb-eye m-r-5 font-weight-300" aria-hidden="true"></i>
											[field:click/]			</span>
									</p>
								</div>
							</li>