
<field:username itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="60" page="">
</field:username>

<field:phone itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="20" page="">
</field:phone>

<field:email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="50" page="">
</field:email>

<field:contactway itemname="联系方式" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="split">
</field:contactway>
