<li class="shown">
										<div class="card card-shadow">
											<figure class="card-header cover">
												<a href="[field:arcurl/]" title="[field:title/]" target=_self>
													<img class="cover-image"     data-original="[field:picname/]" alt="[field:title/]" height='100'>
												</a>
											</figure>
											<h4 class="card-title m-0 p-x-10 font-size-16 text-xs-center">
												<a href="[field:arcurl/]" title="[field:title/]" class="block" target=_self>[field:title/]</a>
												<p class='m-b-0 m-t-5 red-600'></p>
											</h4>
										</div>
									</li>