<li class='masonry-child'>
                                        <a href='[field:arcurl/]' title='[field:title/]' class='block m-b-0' target='_blank'>
                                            <img src="[field:picname/]" class='cover-image' alt='[field:title/]' height='100'></a>
                                        <h4 class='m-t-10 m-b-0 font-size-14 text-md-center'>
                                            <a href='[field:arcurl/]' title='[field:title/]' target='_blank'>[field:title/]</a>
                                        </h4>
                                    </li>