<?php
$z[0]=Array("field","",333,362);
$z[0][4]=array();
$z[0][4]['name']="position";
$z[1]=Array("channel","\r\n                        <li>\r\n                            <a href=\"[field:typelink/]\" title=\"[field:typename/]\" \r\n                            class=' link'>[field:typename/]</a>\r\n                        </li>\r\n                        ",639,1029);
$z[1][4]=array();
$z[1][4]['row']="5";
$z[1][4]['type']="son";
$z[1][4]['currentstyle']="<li><a href='~typelink~' class='active link'>~typename~</a> </li>";

?>